import os

lines = []
lines.append("<!DOCTYPE html>")
lines.append("<html lang='pt-br'>")
lines.append("<head>")
lines.append("<meta charset='UTF-8'>")
lines.append("<meta name='viewport' content='width=device-width, initial-scale=1.0'>")
lines.append("<title>MoneyLayer Enterprise</title>")
lines.append("<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css'>")
lines.append("<style>")
lines.append(".badge-social { background:#e8f5e9; color:#2e7d32; padding:2px 8px; border-radius:4px; font-weight:bold; font-size: 0.8em; }")
lines.append(".badge-entrada { background:#e3f2fd; color:#1565c0; padding:2px 8px; border-radius:4px; font-size: 0.8em; }")
lines.append(".cta-box { background: #f0f0f0; padding: 20px; border-radius: 8px; text-align: center; margin-bottom: 20px; }")
lines.append("</style>")
lines.append("</head>")
lines.append("<body>")
lines.append("<main class='container'>")
lines.append("<nav><ul><li><strong>MoneyLayer 2.0</strong></li></ul></nav>")
lines.append("<div class='grid'>")
lines.append("<article>")
lines.append("<header>Fundo Social</header>")
lines.append("<h1 style='margin-bottom:0'>{{ saldo_formatado }}</h1>")
lines.append("</article>")
lines.append("<article class='cta-box'>")
lines.append("<header>Faça a Economia Girar</header>")
lines.append("<p>Simule uma venda real de R$ 10,00</p>")
lines.append("<form action='/create-checkout-session' method='POST'>")
lines.append("<button type='submit' role='button' class='contrast'>💳 Pagar R$ 10,00</button>")
lines.append("</form>")
lines.append("</article>")
lines.append("</div>")
lines.append("<h3>📊 Auditoria (Últimas 10 Transações)</h3>")
lines.append("<figure>")
lines.append("<table role='grid'>")
lines.append("<thead><tr><th>Data</th><th>Tipo</th><th>Valor</th><th>Detalhes</th></tr></thead>")
lines.append("<tbody>")
lines.append("{% for item in extrato %}")
lines.append("<tr>")
lines.append("<td>{{ item[0].strftime('%d/%m %H:%M') }}</td>")
lines.append("<td>")
lines.append("{% if item[1] == 'ENTRADA' %}<span class='badge-entrada'>RECEITA</span>")
lines.append("{% else %}<span class='badge-social'>SOCIAL ❤️</span>{% endif %}")
lines.append("</td>")
lines.append("<td>R$ {{ '%.2f'|format(item[2]) }}</td>")
lines.append("<td>{{ item[3] }}</td>")
lines.append("</tr>")
lines.append("{% endfor %}")
lines.append("</tbody>")
lines.append("</table>")
lines.append("</figure>")
lines.append("</main>")
lines.append("</body>")
lines.append("</html>")

with open("templates/index.html", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("✅ SUCESSO: Arquivo index.html reconstruído!")
